version: 2.1
orbs:
  bundle-install: toshimaru/bundle-install@x.y.z
  heroku: circleci/heroku@1.0.1 # Use the Heroku orb in your config
jobs:
  rspec:
    docker:
      - image: circleci/postgres:11 # database image
        environment: # environment variables for database, it is kind of obvious but it is important that they match with your test config in database.yml
          POSTGRES_USER: postgres
          POSTGRES_DB: bragging-rights-be_test
          POSTGRES_PASSWORD: bragging-rights-be_test
      - image: 'circleci/ruby:2.7.2'
    steps:
      - checkout
      - bundle-install/bundle-install
      - run: bundle exec rspec
